nameL: "Workflow Setup"
description: " A Composite action that abstracts the setup steps (source, ENV setup )"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18
