name: Schedule workflow to run every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'
    # Min , Hour, Day of Month, Month, Day of Week

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, world! This workflow runs every 5 minutes."