name: Build the Pipeline Baby

# Awe so here you will define a trigger that will trigger on a event
on:
  push:
    branches: [ main ] # did not want to create a dev branch so , just imagine this is dev 
  pull_request:
    branches: [ main ]

jobs: # Define the jobs that will run in this workflow this one will be called "build"
  build:
    runs-on: ubuntu-latest

    steps: # Here we define a List of sequential steps to run in this job
        # Step 1: Source the Code 
      - name: Checkout code
        uses: actions/checkout@v3

        # Step 2: Setup the Environment and Install Dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

        # Step 3 Format and Link Code
      - name: Format check
        run: npm run format

      - name: Lint code
        run: npm run lint

        # Step 4 Compile code
      - name: Compile code (noop)
        run: echo "No compile step needed"

        # Step 5: Run Tests
      - name: Run tests
        run: npm test