name: Build the Pipeline Baby

# Awe so here you will define the event that will trigger the Workflow 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Step 1: Source the Code 
      - name: Checkout code
        uses: actions/checkout@v3

        # Step 2: Setup the Environment and Install Dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

        # Step 3 Format and Link Code
        
        # Step 4 Compile code
      - name: Compile code (noop)
        run: echo "No compile step needed"

        #Step 5: Run Tests
      - name: Run tests
        run: npm test