name: Build the Pipeline Baby
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: 
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

      # Abstracts Two Steps: Checkout, Setup Node.js
      - name: Setup Workflow
        uses: ./.github/actions/setup

      - name: Install Dependencies
        run: npm ci
        
      # Abstracts One step: Format and Lint Code
      - name: Format and Lint Code
        uses: ./.github/actions/format

      - name: Compile code
        run: echo "No compile step needed"

      - name: Run tests
        run: npm test
  # We abstract those steps into a Composite function because we might want to re-ues these steps in teh fucture 
  # for other workflows, like the deploy workflow, where we will  have to setup the workflow, install dependencies, and run tests.
